apiVersion: v1
kind: PersistentVolume
metadata:
  name: covidopv
spec:
  storageClassName: covidostorageclass
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/u01/data"

    